// Delivery rates data - update this file when rates change
export type DeliveryRate = {
  city: string;
  rate: number;
};

export const DELIVERY_RATES: DeliveryRate[] = [
  { city: "4 NO JEETPUR", rate: 225 },
  { city: "AANBU KHAIRENI TANAHU", rate: 200 },
  { city: "ACHHAM", rate: 275 },
  { city: "ADANABARI", rate: 225 },
  { city: "ADARSHA KOTWAL DANG", rate: 225 },
  { city: "AESELUKHARKA KAVREPALANCHOK", rate: 200 },
  { city: "AGRABODI JHAPA", rate: 200 },
  { city: "AITABARE", rate: 225 },
  { city: "AMAHIYA", rate: 225 },
  { city: "AMARGADHI", rate: 275 },
  { city: "AMARPURI", rate: 220 },
  { city: "AMILIYA", rate: 220 },
  { city: "AMLEKHGUNJ", rate: 225 },
  { city: "AMUWA", rate: 220 },
  { city: "ANARMANI", rate: 225 },
  { city: "ANWALA MAHENDRA", rate: 225 },
  { city: "ARANIKO RAJMARG", rate: 160 },
  { city: "ARGHAKHANCHI", rate: 240 },
  { city: "ARNAHA", rate: 225 },
  { city: "ARUN RURAL MUNICIPALITY", rate: 250 },
  { city: "ARUNKHOLA", rate: 225 },
  { city: "ATTARIYA", rate: 220 },
  { city: "AURAHI MAHOTTARI", rate: 220 },
  { city: "AURABARMA", rate: 240 },
  { city: "AARUBARI", rate: 225 },
  { city: "BAGCHAUR", rate: 240 },
  { city: "BAGLUNG", rate: 220 },
  { city: "BAHRABISE", rate: 240 },
  { city: "BAHUNDANGI", rate: 250 },
  { city: "BAIKUNTHE", rate: 225 },
  { city: "BAIJNATH BANKE", rate: 225 },
  { city: "BAITADI", rate: 275 },
  { city: "BAJRABARAHI", rate: 160 },
  { city: "BAJURA", rate: 300 },
  { city: "BALAJU", rate: 140 },
  { city: "BALEPHI", rate: 200 },
  { city: "BALETAXAR", rate: 240 },
  { city: "BALKUMARI", rate: 140 },
  { city: "BALKOT", rate: 160 },
  { city: "BALUWATAR", rate: 140 },
  { city: "BANDIPUR TANAHUN", rate: 240 },
  { city: "BANEPA", rate: 160 },
  { city: "BANIYABAZAR", rate: 240 },
  { city: "BANIYANI JHAPA", rate: 240 },
  { city: "BANKE", rate: 225 },
  { city: "BANSBARI MORANG", rate: 175 },
  { city: "BANSAGADHI", rate: 240 },
  { city: "BANSKOT", rate: 240 },
  { city: "BARAHACHHETRA", rate: 200 },
  { city: "BARAHATHAWA SARLAHI", rate: 220 },
  { city: "BARAHBISE", rate: 240 },
  { city: "BARAHKSHETRA", rate: 200 },
  { city: "BARAL", rate: 225 },
  { city: "BARA", rate: 220 },
  { city: "BARDAGHAT", rate: 210 },
  { city: "BARDIBAS", rate: 210 },
  { city: "BARDIYA", rate: 240 },
  { city: "BARHABISE", rate: 240 },
  { city: "BARIYAPATTI SIRAHA", rate: 220 },
  { city: "BARIYARPUR", rate: 225 },
  { city: "BARJU SUNSARI", rate: 225 },
  { city: "BASANTAPUR TERHATHUM", rate: 250 },
  { city: "BASTIPUR", rate: 225 },
  { city: "BATESHWOR", rate: 225 },
  { city: "BAUDHA", rate: 140 },
  { city: "BEDKOT KANCHANPUR", rate: 240 },
  { city: "BELAURI KANCHANPUR", rate: 240 },
  { city: "BELBARI MORANG", rate: 175 },
  { city: "BELTAR UDAIPUR", rate: 220 },
  { city: "BENI", rate: 240 },
  { city: "BESISAHAR LAMJUNG", rate: 220 },
  { city: "BHAINSEPATI", rate: 140 },
  { city: "BHAIRAHAWA", rate: 210 },
  { city: "BHAJANI KAILALI", rate: 240 },
  { city: "BHAKTAPUR", rate: 150 },
  { city: "BHANGAHA", rate: 220 },
  { city: "BHARATPUR", rate: 190 },
  { city: "BHEDETAR", rate: 240 },
  { city: "BHERI", rate: 275 },
  { city: "BHIMAD", rate: 220 },
  { city: "BHIMESHWOR", rate: 200 },
  { city: "BHIMDATTA KANCHANPUR", rate: 240 },
  { city: "BHIMPHEDI", rate: 180 },
  { city: "BHOJPUR", rate: 250 },
  { city: "BHOTE KOSI", rate: 200 },
  { city: "BHUDHANAGIN KANCHANPUR", rate: 240 },
  { city: "BIGU", rate: 200 },
  { city: "BIHIRIMELA MORANG", rate: 200 },
  { city: "BIJAYA DASHAMI BARA", rate: 220 },
  { city: "BIJAYAPUR DHARAN", rate: 200 },
  { city: "BIJAYNAGAR BANKE", rate: 225 },
  { city: "BIJUWAR", rate: 225 },
  { city: "BIRATNAGAR", rate: 180 },
  { city: "BIRENDRANAGAR", rate: 250 },
  { city: "BIRGANJ", rate: 210 },
  { city: "BIRGUNJ", rate: 210 },
  { city: "BIRTAMOD", rate: 200 },
  { city: "BISHNUPADUKA", rate: 225 },
  { city: "BODEBARSAIN", rate: 240 },
  { city: "BOUDDHA", rate: 140 },
  { city: "BP HIGHWAY", rate: 160 },
  { city: "BUDHANILKANTHA", rate: 140 },
  { city: "BUDHIGANGA BAJURA", rate: 300 },
  { city: "BUDDHASHANTI", rate: 225 },
  { city: "BUDOL BAJURA", rate: 300 },
  { city: "BULINGTAR NAWALPUR", rate: 210 },
  { city: "BUNGAMATI", rate: 150 },
  { city: "BUTWAL", rate: 210 },
  { city: "CHAINPUR", rate: 250 },
  { city: "CHANGUNARAYAN", rate: 160 },
  { city: "CHAPAKOT SYANGJA", rate: 220 },
  { city: "CHAUDANDIGADHI UDAIPUR", rate: 220 },
  { city: "CHAUDHARY TOL", rate: 220 },
  { city: "CHANDRAGIRI", rate: 150 },
  { city: "CHANDRAGIRI HILLS", rate: 150 },
  { city: "CHANDRANIGAHAPUR", rate: 220 },
  { city: "CHAPAGAUN", rate: 150 },
  { city: "CHAUTARA", rate: 180 },
  { city: "CHEPANG MAKWANPUR", rate: 200 },
  { city: "CHHINCHU", rate: 200 },
  { city: "CHILAUNEBAS KANCHANPUR", rate: 240 },
  { city: "CHISAPANI KAILALI", rate: 240 },
  { city: "CHITLANG", rate: 180 },
  { city: "CHITWAN", rate: 190 },
  { city: "CHOBHAR", rate: 150 },
  { city: "CHYASAL", rate: 140 },
  { city: "CHUHANDANDA", rate: 220 },
  { city: "CHULACHULI ILAM", rate: 240 },
  { city: "DADHIKOT BHAKTAPUR", rate: 160 },
  { city: "DAILEKH", rate: 250 },
  { city: "DAKSHINKALI", rate: 150 },
  { city: "DALIT TOL", rate: 220 },
  { city: "DAMAK", rate: 200 },
  { city: "DAMAULI", rate: 220 },
  { city: "DAMAN", rate: 200 },
  { city: "DANFE KHARKA", rate: 240 },
  { city: "DANG", rate: 225 },
  { city: "DANUSHA", rate: 220 },
  { city: "DARCHULA", rate: 300 },
  { city: "DARBANG", rate: 240 },
  { city: "DARJILING ROAD JHAPA", rate: 240 },
  { city: "DASARATH CHAND BAITADI", rate: 275 },
  { city: "DASNAMI MAHENDRANAGAR", rate: 240 },
  { city: "DATIDANDA KAVRE", rate: 200 },
  { city: "DAUNNE NAWALPUR", rate: 210 },
  { city: "DAUNGHAT", rate: 240 },
  { city: "DEVDAHA RUPANDEHI", rate: 210 },
  { city: "DEVGHAT", rate: 210 },
  { city: "DHADHING", rate: 180 },
  { city: "DHADING BESI", rate: 180 },
  { city: "DHAKA GAUN", rate: 140 },
  { city: "DHAKDHAI KAILALI", rate: 240 },
  { city: "DHALKEBAR", rate: 220 },
  { city: "DHANBAD SIRAHA", rate: 220 },
  { city: "DHANGADHI", rate: 240 },
  { city: "DHANKUTA", rate: 240 },
  { city: "DHANUSHA", rate: 220 },
  { city: "DHAPAKHEL", rate: 150 },
  { city: "DHAPASI", rate: 140 },
  { city: "DHARAN", rate: 200 },
  { city: "DHARKE DHADING", rate: 180 },
  { city: "DHIKIDAHA KAILALI", rate: 240 },
  { city: "DHOBIGHAT", rate: 140 },
  { city: "DHULIKHEL", rate: 160 },
  { city: "DHUNCHE RASUWA", rate: 220 },
  { city: "DHUNIBESI", rate: 180 },
  { city: "DIKTEL KHOTANG", rate: 250 },
  { city: "DIPAYAL DOTI", rate: 275 },
  { city: "DOBHAN SYANGJA", rate: 220 },
  { city: "DOLAKHA", rate: 200 },
  { city: "DOLALGHAT", rate: 160 },
  { city: "DOTI", rate: 275 },
  { city: "DUDHAULI SINDHULI", rate: 210 },
  { city: "DUDKOSHI SOLUKHUMBU", rate: 260 },
  { city: "DULLU DAILEKH", rate: 250 },
  { city: "DUMARWANA BARA", rate: 220 },
  { city: "DUHABI", rate: 200 },
  { city: "DUMKAULI NAWALPUR", rate: 210 },
  { city: "DUNAMUHAN BANKE", rate: 225 },
  { city: "DUNAI DOLPA", rate: 300 },
  { city: "DURGAULI BANKE", rate: 225 },
  { city: "EAST NAWALPARASI", rate: 210 },
  { city: "EKAMBA JHAPA", rate: 240 },
  { city: "FAKEPHOKTHUM PANCHTHAR", rate: 250 },
  { city: "FAKHEL KANCHANPUR", rate: 240 },
  { city: "FALELUNG PANCHTHAR", rate: 250 },
  { city: "FALGUNANDA PANCHTHAR", rate: 250 },
  { city: "FARPHING", rate: 150 },
  { city: "FATTEPUR BARA", rate: 220 },
  { city: "FEDIKHOLA SYANGJA", rate: 220 },
  { city: "FIDIM PANCHTHAR", rate: 250 },
  { city: "GADHI DARCHULA", rate: 300 },
  { city: "GADHIMAI BARA", rate: 220 },
  { city: "GADOL", rate: 240 },
  { city: "GAIDAKOT", rate: 210 },
  { city: "GAJURI DHADING", rate: 180 },
  { city: "GALYANG SYANGJA", rate: 220 },
  { city: "GAMGADHI MUGU", rate: 300 },
  { city: "GANESHMAN CHARNATH HUMLA", rate: 300 },
  { city: "GANAPUR", rate: 220 },
  { city: "GANGAJAMUNA DHANUSHA", rate: 220 },
  { city: "GANGAPUR BARA", rate: 220 },
  { city: "GARUDA RAUTAHAT", rate: 220 },
  { city: "GAUR", rate: 220 },
  { city: "GAURADAHA JHAPA", rate: 240 },
  { city: "GAURIGANJ JHAPA", rate: 240 },
  { city: "GAURIGUNJ", rate: 225 },
  { city: "GAURISHANKAR DOLAKHA", rate: 200 },
  { city: "GAUSHALA MAHOTTARI", rate: 220 },
  { city: "GHANTAGHAR", rate: 140 },
  { city: "GHODAGHODI KAILALI", rate: 240 },
  { city: "GHORAHI", rate: 225 },
  { city: "GHYAMPESAL", rate: 200 },
  { city: "GIRKHUWA BANKE", rate: 225 },
  { city: "GODAITA", rate: 240 },
  { city: "GODAWARI", rate: 150 },
  { city: "GOKARNESHWOR", rate: 140 },
  { city: "GOLFUTAR", rate: 140 },
  { city: "GOLMADHI", rate: 160 },
  { city: "GONGABU", rate: 140 },
  { city: "GOPALGANJ", rate: 225 },
  { city: "GORKHA", rate: 210 },
  { city: "GOTHATAR", rate: 140 },
  { city: "GOTHGAUN", rate: 210 },
  { city: "GULARIYA BARDIYA", rate: 240 },
  { city: "GULMI", rate: 230 },
  { city: "GUNDU PANCHTHAR", rate: 250 },
  { city: "GURANSHE PHEDI", rate: 160 },
  { city: "GYANESHWOR", rate: 140 },
  { city: "HAKU KAVRE", rate: 200 },
  { city: "HALCHOWK", rate: 140 },
  { city: "HALDIBARI JHAPA", rate: 240 },
  { city: "HALESI KHOTANG", rate: 250 },
  { city: "HALKHORIYA BARA", rate: 220 },
  { city: "HAMRO GAUN", rate: 220 },
  { city: "HANDIGAUN", rate: 140 },
  { city: "HANUMAN DHOKA", rate: 140 },
  { city: "HARIPUR", rate: 220 },
  { city: "HARINAGARA KAILALI", rate: 240 },
  { city: "HARIWAN SARLAHI", rate: 220 },
  { city: "HARKAPUR", rate: 220 },
  { city: "HATIYA", rate: 240 },
  { city: "HATWAGADHI BAITADI", rate: 275 },
  { city: "HATTIBAN", rate: 150 },
  { city: "HELAMBU SINDHUPALCHOWK", rate: 220 },
  { city: "HEMJA KASKI", rate: 210 },
  { city: "HETAUDA", rate: 190 },
  { city: "HILIHANG TANAHUN", rate: 220 },
  { city: "HILE DHANKUTA", rate: 240 },
  { city: "HIMCHULI MUSTANG", rate: 260 },
  { city: "HUMLA", rate: 300 },
  { city: "ICHCHHAKAMANA CHITWAN", rate: 190 },
  { city: "ILAM", rate: 240 },
  { city: "IMADOL", rate: 140 },
  { city: "INDRAWATI SINDHUPALCHOWK", rate: 220 },
  { city: "INDRESHWOR", rate: 200 },
  { city: "INARUWA", rate: 200 },
  { city: "INAYAT DANG", rate: 225 },
  { city: "ISHANATH RAUTAHAT", rate: 220 },
  { city: "ITAHARI", rate: 200 },
  { city: "JADA BHAWARI", rate: 220 },
  { city: "JADIBUTI", rate: 140 },
  { city: "JAJARKOT", rate: 260 },
  { city: "JALESWAR", rate: 220 },
  { city: "JALESHWOR MAHOTTARI", rate: 220 },
  { city: "JALTHAL KAILALI", rate: 240 },
  { city: "JAMUNE BANKE", rate: 225 },
  { city: "JANAKPUR", rate: 220 },
  { city: "JANAKI MAHOTTARI", rate: 220 },
  { city: "JANAPRIYA TOL", rate: 220 },
  { city: "JANKIDEVI BANKE", rate: 225 },
  { city: "JARSINGPAUWA PARSA", rate: 220 },
  { city: "JAWALAMUKHI DHADING", rate: 180 },
  { city: "JAWLAKHEL", rate: 140 },
  { city: "JEETPUR", rate: 225 },
  { city: "JEETPUR BARA", rate: 220 },
  { city: "JEETPUR SIMARA", rate: 220 },
  { city: "JETTHUL BAITADI", rate: 275 },
  { city: "JHANKRIBAS", rate: 240 },
  { city: "JHAPA", rate: 240 },
  { city: "JHIJHARI BANKE", rate: 225 },
  { city: "JHORAHAT MORANG", rate: 200 },
  { city: "JHULAGHAT", rate: 275 },
  { city: "JHUMKA SINDHULI", rate: 210 },
  { city: "JIRI DOLAKHA", rate: 220 },
  { city: "JITPUR BARA", rate: 220 },
  { city: "JOGBANI", rate: 220 },
  { city: "JOMSOM", rate: 260 },
  { city: "JORPATI", rate: 140 },
  { city: "JUGEDI BAZAR RAUTAHAT", rate: 220 },
  { city: "JUMLA", rate: 280 },
  { city: "JYAMIRGADHI ACHHAM", rate: 275 },
  { city: "KAGESHWARI MANAHARA", rate: 140 },
  { city: "KAILALI", rate: 240 },
  { city: "KAILARI KAILALI", rate: 240 },
  { city: "KAKADBHITTA", rate: 240 },
  { city: "KALANKI", rate: 140 },
  { city: "KALIKA CHITWAN", rate: 190 },
  { city: "KALIKASTHAN", rate: 140 },
  { city: "KALIMATI", rate: 140 },
  { city: "KAMALADI", rate: 140 },
  { city: "KAMALBINAYAK", rate: 160 },
  { city: "KAMALAMAI SINDHULI", rate: 210 },
  { city: "KAMALPOKHARI", rate: 140 },
  { city: "KAMDI MORANG", rate: 200 },
  { city: "KAMEROTAR OKHALDHUNGA", rate: 240 },
  { city: "KANCHANPUR", rate: 240 },
  { city: "KANCHANRUP", rate: 220 },
  { city: "KANKAI JHAPA", rate: 240 },
  { city: "KANEPOKHARI MORANG", rate: 200 },
  { city: "KAPAN", rate: 140 },
  { city: "KAPILVASTU", rate: 225 },
  { city: "KARAIYAMAI BARA", rate: 220 },
  { city: "KARNALI", rate: 280 },
  { city: "KARTIKE OKHALDHUNGA", rate: 240 },
  { city: "KASKI", rate: 210 },
  { city: "KASTHALI CHITWAN", rate: 190 },
  { city: "KATARI UDAYAPUR", rate: 220 },
  { city: "KATHMANDU", rate: 140 },
  { city: "KATUNJE JHAPA", rate: 240 },
  { city: "KAUSHALTAR", rate: 160 },
  { city: "KAVREPALANCHOK", rate: 200 },
  { city: "KERABARI MORANG", rate: 200 },
  { city: "KERUNG", rate: 260 },
  { city: "KHAJURA BANKE", rate: 225 },
  { city: "KHANIKHOLA DHADING", rate: 180 },
  { city: "KHANAR RUPANDEHI", rate: 210 },
  { city: "KHANDBARI SANKHUWASABHA", rate: 250 },
  { city: "KHOKANA", rate: 150 },
  { city: "KHOPASI KAVRE", rate: 200 },
  { city: "KHOTANG", rate: 250 },
  { city: "KHUDUNABARI JHAPA", rate: 240 },
  { city: "KHUMALTAR", rate: 140 },
  { city: "KHUSIBUN NUWAKOT", rate: 180 },
  { city: "KIRTIPUR", rate: 150 },
  { city: "KOHALPUR BANKE", rate: 225 },
  { city: "KOHI JHAPA", rate: 240 },
  { city: "KOLHABI BARA", rate: 220 },
  { city: "KOPUNDOL", rate: 140 },
  { city: "KOTESHWOR", rate: 140 },
  { city: "KOSHI", rate: 200 },
  { city: "KUMAL TOL", rate: 220 },
  { city: "KUNTABESI KAVRE", rate: 200 },
  { city: "KUSMA PARBAT", rate: 230 },
  { city: "KUSUM KHOLA SINDHUPALCHOWK", rate: 220 },
  { city: "KUSUNTAR CHITWAN", rate: 190 },
  { city: "KWABAHAL", rate: 140 },
  { city: "LAHAN", rate: 220 },
  { city: "LALBANDI SARLAHI", rate: 220 },
  { city: "LALITPUR", rate: 140 },
  { city: "LAMAHI DANG", rate: 225 },
  { city: "LAMJUNG", rate: 220 },
  { city: "LAMKI KAILALI", rate: 240 },
  { city: "LAZIMPAT", rate: 140 },
  { city: "LEKHNATH KASKI", rate: 210 },
  { city: "LETANG MORANG", rate: 200 },
  { city: "LUMBINI", rate: 210 },
  { city: "MACHHAPUCHHRE KASKI", rate: 210 },
  { city: "MADHYABINDU", rate: 210 },
  { city: "MADHYAPUR THIMI", rate: 150 },
  { city: "MAHABHARAT TOL", rate: 220 },
  { city: "MAHAKALI", rate: 275 },
  { city: "MAHADEVSTHAN", rate: 200 },
  { city: "MAHAGADHIMAI BARA", rate: 220 },
  { city: "MAHAKAVI DEVKOTA CHOWK", rate: 140 },
  { city: "MAHALAXMI IMADOL", rate: 140 },
  { city: "MAHARAJGUNJ", rate: 140 },
  { city: "MAHENDRANAGAR", rate: 240 },
  { city: "MAHESH KHOLA SYANGJA", rate: 220 },
  { city: "MAHESHPUR KAILALI", rate: 240 },
  { city: "MAHOTTARI", rate: 220 },
  { city: "MAI ILAM", rate: 240 },
  { city: "MAITIGHAR", rate: 140 },
  { city: "MAITIDEVI", rate: 140 },
  { city: "MAKAWANPUR", rate: 190 },
  { city: "MALANGAWA SARLAHI", rate: 220 },
  { city: "MALDHUNGA", rate: 220 },
  { city: "MALEKHU", rate: 180 },
  { city: "MALEPATAN", rate: 210 },
  { city: "MANGALBARE ILAM", rate: 240 },
  { city: "MANGALSEN ACHHAM", rate: 275 },
  { city: "MANMOHAN MEMORIAL TEACHING HOSPITAL", rate: 140 },
  { city: "MANMAIJU", rate: 140 },
  { city: "MANTHALI RAMECHHAP", rate: 220 },
  { city: "MATATIRTHA", rate: 150 },
  { city: "MAULAPUR RAUTAHAT", rate: 220 },
  { city: "MECHINAGAR JHAPA", rate: 240 },
  { city: "MEGHAULI CHITWAN", rate: 190 },
  { city: "MELAMCHI SINDHUPALCHOWK", rate: 220 },
  { city: "MIRCHAIYA SIRAHA", rate: 220 },
  { city: "MOHAN DANG", rate: 225 },
  { city: "MORANG", rate: 200 },
  { city: "MUGLIN", rate: 200 },
  { city: "MUGLING", rate: 200 },
  { city: "MUGU", rate: 300 },
  { city: "MULPANI", rate: 140 },
  { city: "MUNGELI KANCHANPUR", rate: 240 },
  { city: "MURKUCHOK BAJHANG", rate: 290 },
  { city: "MUSTANG", rate: 260 },
  { city: "MYAGDE TANAHUN", rate: 220 },
  { city: "NAGARJUN", rate: 140 },
  { city: "NAGDAHA LALITPUR", rate: 140 },
  { city: "NAIKAP", rate: 140 },
  { city: "NALLU KAVRE", rate: 200 },
  { city: "NAMCHE BAZAAR", rate: 280 },
  { city: "NAMO BUDDHA", rate: 160 },
  { city: "NANGLEBHARE LALITPUR", rate: 150 },
  { city: "NARAYANGARH", rate: 190 },
  { city: "NARAYANGHAT", rate: 190 },
  { city: "NARAYANTHAN", rate: 140 },
  { city: "NAWALPARASI", rate: 210 },
  { city: "NAWALPUR", rate: 210 },
  { city: "NAXAL", rate: 140 },
  { city: "NEPALGUNJ", rate: 225 },
  { city: "NEW BANESHWOR", rate: 140 },
  { city: "NEW ROAD", rate: 140 },
  { city: "NIJGADH BARA", rate: 220 },
  { city: "NUWAKOT", rate: 180 },
  { city: "OKHALDUNGA", rate: 240 },
  { city: "OKHARPAUWA NUWAKOT", rate: 180 },
  { city: "OLD BANESHWOR", rate: 140 },
  { city: "PACHTHAR ILAM", rate: 240 },
  { city: "PACHKHAL KAVRE", rate: 200 },
  { city: "PACHRAUTA MAHOTTARI", rate: 220 },
  { city: "PALPA", rate: 220 },
  { city: "PANAUTI", rate: 160 },
  { city: "PANCHTHAR", rate: 250 },
  { city: "PANCHKHAL", rate: 200 },
  { city: "PANDAVKHANI", rate: 220 },
  { city: "PANITANKI", rate: 240 },
  { city: "PARBAT", rate: 230 },
  { city: "PARSA", rate: 220 },
  { city: "PARSAGADHI", rate: 220 },
  { city: "PASHUPATINATH", rate: 140 },
  { city: "PASIKOT ILAM", rate: 240 },
  { city: "PATAN", rate: 140 },
  { city: "PATHARI MORANG", rate: 200 },
  { city: "PATHIVARA TAPLEJUNG", rate: 260 },
  { city: "PATHLAIYA BARA", rate: 220 },
  { city: "PAUDEL GAUN", rate: 220 },
  { city: "PHAKTANLUNG PANCHTHAR", rate: 250 },
  { city: "PHALELUNG PANCHTHAR", rate: 250 },
  { city: "PHAPARTHUM ILAM", rate: 240 },
  { city: "PHAPLU SOLUKHUMBU", rate: 260 },
  { city: "PHIDIM", rate: 250 },
  { city: "PHIKKAL ILAM", rate: 240 },
  { city: "PHULBARI MORANG", rate: 200 },
  { city: "PHULPINGKATTI PANCHTHAR", rate: 250 },
  { city: "PHUNGLING TAPLEJUNG", rate: 260 },
  { city: "PHUTUNG PANCHTHAR", rate: 250 },
  { city: "PIPARA MAHOTTARI", rate: 220 },
  { city: "PIPARA SIMARA BARA", rate: 220 },
  { city: "PIPARIYA KAILALI", rate: 240 },
  { city: "PITHUWA MAHOTTARI", rate: 220 },
  { city: "POKHARA", rate: 210 },
  { city: "POKHARI BHANJYANG", rate: 220 },
  { city: "POKHARICHAURI DHADING", rate: 180 },
  { city: "PRATAPUR PARSA", rate: 220 },
  { city: "PUBUNG PANCHTHAR", rate: 250 },
  { city: "PULCHOWK", rate: 140 },
  { city: "PURANO BANESHWOR", rate: 140 },
  { city: "PURNA GAUN", rate: 220 },
  { city: "PYUTHAN", rate: 240 },
  { city: "RAINAS LAMJUNG", rate: 220 },
  { city: "RAINADEVI CHITWAN", rate: 190 },
  { city: "RAJBIRAJ SAPTARI", rate: 220 },
  { city: "RAJDEVI", rate: 140 },
  { city: "RAMACHHAP", rate: 220 },
  { city: "RAMDHUNI SUNSARI", rate: 200 },
  { city: "RAMGRAM NAWALPARASI", rate: 210 },
  { city: "RAMPUR PALPA", rate: 220 },
  { city: "RAMSHAHPATH", rate: 140 },
  { city: "RAMPURDHAMASH PALPA", rate: 220 },
  { city: "RANGELI MORANG", rate: 200 },
  { city: "RANIBAN", rate: 140 },
  { city: "RANIPAUWA", rate: 210 },
  { city: "RAPTI", rate: 225 },
  { city: "RASUWA", rate: 220 },
  { city: "RATMATE LALITPUR", rate: 150 },
  { city: "RATOMATE", rate: 150 },
  { city: "RATNANAGAR CHITWAN", rate: 190 },
  { city: "RAUTAHAT", rate: 220 },
  { city: "RAVIBHAWAN", rate: 140 },
  { city: "RAYAS ROLPA", rate: 250 },
  { city: "RAJAPUR BARDIYA", rate: 240 },
  { city: "RISHING TANAHUN", rate: 220 },
  { city: "RISHIHAWA KAPILBASTU", rate: 225 },
  { city: "ROLPA", rate: 250 },
  { city: "RUKUM", rate: 260 },
  { city: "RUKUM WEST", rate: 260 },
  { city: "RUPANDEHI", rate: 210 },
  { city: "RUPA KASKI", rate: 210 },
  { city: "SAGARMATHA", rate: 280 },
  { city: "SAILUNG DOLAKHA", rate: 220 },
  { city: "SAINAMAINA RUPANDEHI", rate: 210 },
  { city: "SAKHUWANANKARKATTI OKHALDHUNGA", rate: 240 },
  { city: "SALERI SOLUKHUMBU", rate: 260 },
  { city: "SAMAKHUSI", rate: 140 },
  { city: "SAMSI BARDIYA", rate: 240 },
  { city: "SANGA", rate: 160 },
  { city: "SANKHUWASABHA", rate: 250 },
  { city: "SANKHU", rate: 150 },
  { city: "SANO BHARYANG MAKWANPUR", rate: 190 },
  { city: "SANO PAILA KAVRE", rate: 200 },
  { city: "SANO THIMI", rate: 150 },
  { city: "SANOTHIMI", rate: 150 },
  { city: "SAPTAKOSHI SAPTARI", rate: 220 },
  { city: "SAPTARI", rate: 220 },
  { city: "SARAWAL BANKE", rate: 225 },
  { city: "SARLAHI", rate: 220 },
  { city: "SATDOBATO", rate: 140 },
  { city: "SATTALE KAVRE", rate: 200 },
  { city: "SATUNGAL", rate: 140 },
  { city: "SIDDHARTHANAGAR RUPANDEHI", rate: 210 },
  { city: "SIDDHICHARAN OKHALDHUNGA", rate: 240 },
  { city: "SIMARA BARA", rate: 220 },
  { city: "SIMIKOT HUMLA", rate: 300 },
  { city: "SIMRAUNGADH BARA", rate: 220 },
  { city: "SINDHUPALCHOK", rate: 220 },
  { city: "SINDHULI", rate: 210 },
  { city: "SINDHULI GADHI", rate: 210 },
  { city: "SINGHIYADEVI BARA", rate: 220 },
  { city: "SIRAHA", rate: 220 },
  { city: "SIRANCHOK GORKHA", rate: 210 },
  { city: "SIRSIYA MORANG", rate: 200 },
  { city: "SISNEKHOLA GULMI", rate: 230 },
  { city: "SITAPAILA", rate: 140 },
  { city: "SOLU CORRIDOR", rate: 260 },
  { city: "SOLUKHUMBU", rate: 260 },
  { city: "SUNDARHARAICHA MORANG", rate: 200 },
  { city: "SUNDARBAZAR LAMJUNG", rate: 220 },
  { city: "SUNDHARA", rate: 140 },
  { city: "SUNSARI", rate: 200 },
  { city: "SUNSARI MORANG DEVELOPMENT REGION", rate: 200 },
  { city: "SURKHET", rate: 250 },
  { city: "SURYA BINAYAK BHAKTAPUR", rate: 160 },
  { city: "SURYODAYA ILAM", rate: 240 },
  { city: "SWAYAMBHU", rate: 140 },
  { city: "SYAFRU RASUWA", rate: 220 },
  { city: "SYANGJA", rate: 220 },
  { city: "TABASUM KAVRE", rate: 200 },
  { city: "TANDI CHITWAN", rate: 190 },
  { city: "TANSEN PALPA", rate: 220 },
  { city: "TAPLEJUNG", rate: 260 },
  { city: "TARKESHWOR", rate: 140 },
  { city: "TATOPANI SINDHUPALCHOWK", rate: 240 },
  { city: "TAULIHAWA KAPILBASTU", rate: 225 },
  { city: "TAUMADHI", rate: 150 },
  { city: "TAUTHALI KATHMANDU", rate: 140 },
  { city: "TEHRATHUM", rate: 250 },
  { city: "TEKANPUR RUPANDEHI", rate: 210 },
  { city: "TEKU", rate: 140 },
  { city: "TEMAL KAVRE", rate: 200 },
  { city: "TERHATHUM", rate: 250 },
  { city: "THAHA MAKWANPUR", rate: 190 },
  { city: "THAKURBABA BARDIYA", rate: 240 },
  { city: "THALI JUMLA", rate: 280 },
  { city: "THAMEL", rate: 140 },
  { city: "THANO BAITADI", rate: 275 },
  { city: "THAPAGAUN KATHMANDU", rate: 140 },
  { city: "THIMI", rate: 150 },
  { city: "TINPIPLE", rate: 140 },
  { city: "TIKAPUR KAILALI", rate: 240 },
  { city: "TINKUNE", rate: 140 },
  { city: "TOKHA", rate: 140 },
  { city: "TRIYUGA UDAIPUR", rate: 220 },
  { city: "TRIBHUVAN INTERNATIONAL AIRPORT", rate: 140 },
  { city: "TRIPURASUNDARI DOLPA", rate: 300 },
  { city: "TRISULI", rate: 180 },
  { city: "TULSIPUR DANG", rate: 225 },
  { city: "TUSAL OKHALDHUNGA", rate: 240 },
  { city: "UDAYAPUR", rate: 220 },
  { city: "URLABARI MORANG", rate: 200 },
  { city: "UTTARGAYA RASUWA", rate: 220 },
  { city: "WALING SYANGJA", rate: 220 },
  { city: "YAMPAPHANT PANCHTHAR", rate: 250 },
];
