// Delivery rates data - updated from Gaaubesi API on December 8, 2025
export type DeliveryRate = {
  city: string;
  rate: number;
};

export const DELIVERY_RATES: DeliveryRate[] = [
  { city: "4 NO JEETPUR", rate: 225.0 },
  { city: "AANBU KHAIRENI TANAHU", rate: 200.0 },
  { city: "AITABARE MORANG", rate: 225.0 },
  { city: "AMARAI ARGHAKHANCHI", rate: 245.0 },
  { city: "AMARGADHI", rate: 275.0 },
  { city: "AMLEKHGUNJ", rate: 225.0 },
  { city: "AMUWA", rate: 225.0 },
  { city: "ARNAHA", rate: 225.0 },
  { city: "ARUNKHOLA", rate: 225.0 },
  { city: "ATTARIYA", rate: 200.0 },
  { city: "AURABANI", rate: 225.0 },
  { city: "AURAHI MAHOTTARI", rate: 225.0 },
  { city: "BADNIHAR", rate: 225.0 },
  { city: "BAGLUNG", rate: 200.0 },
  { city: "BAGMARA", rate: 170.0 },
  { city: "BAHRABISE", rate: 250.0 },
  { city: "BAHUNDANGI", rate: 250.0 },
  { city: "BAHUNI", rate: 225.0 },
  { city: "BAIGUNDHURA JHAPA", rate: 225.0 },
  { city: "BALAWA", rate: 225.0 },
  { city: "BALETAXAR", rate: 250.0 },
  { city: "BANDIPUR TANAHUN", rate: 225.0 },
  { city: "BANEPA", rate: 150.0 },
  { city: "BANIYANI JHAPA", rate: 225.0 },
  { city: "BANSAGADHI", rate: 250.0 },
  { city: "BANSBARI MORANG", rate: 175.0 },
  { city: "BARAHATHAWA SARLAHI", rate: 250.0 },
  { city: "BARDAGHAT", rate: 200.0 },
  { city: "BARDIBAS", rate: 200.0 },
  { city: "BARIYAPATTI SIRAHA", rate: 250.0 },
  { city: "BARIYARPUR", rate: 225.0 },
  { city: "BARJU SUNSARI", rate: 225.0 },
  { city: "BASABASAHI", rate: 225.0 },
  { city: "BASANTAPUR TERHATHUM", rate: 250.0 },
  { city: "BASTIPUR", rate: 225.0 },
  { city: "BASTIPUR MAKAWANPUR", rate: 225.0 },
  { city: "BATESHWOR", rate: 225.0 },
  { city: "BATTAR BAZAR", rate: 225.0 },
  { city: "BAUNIYA", rate: 225.0 },
  { city: "BAYALBAS", rate: 250.0 },
  { city: "BELAURI", rate: 250.0 },
  { city: "BELBARI", rate: 200.0 },
  { city: "BELDANDI KANCHANPUR", rate: 250.0 },
  { city: "BELDANGI JHAPA", rate: 250.0 },
  { city: "BELSOT", rate: 250.0 },
  { city: "BELTAR UDAYAPUR", rate: 250.0 },
  { city: "BENI", rate: 200.0 },
  { city: "BESI SAHAR", rate: 250.0 },
  { city: "BHADRAPUR", rate: 200.0 },
  { city: "BHAGWANPUR SIRAHA", rate: 250.0 },
  { city: "BHAIRAHAWA", rate: 150.0 },
  { city: "BHAJANI", rate: 225.0 },
  { city: "BHAKUNDE BESI KAVRE", rate: 225.0 },
  { city: "BHALUBANG", rate: 225.0 },
  { city: "BHALWARI RUPANDEHI", rate: 225.0 },
  { city: "BHANDARA CHITWAN", rate: 250.0 },
  { city: "BHANGAHA", rate: 225.0 },
  { city: "BHANTABARI SUNSARI", rate: 250.0 },
  { city: "BHARATPUR", rate: 175.0 },
  { city: "BHEDETAR SUNSARI", rate: 275.0 },
  { city: "BHIMAD TANAHU", rate: 250.0 },
  { city: "BHIMAN SINDHULI", rate: 250.0 },
  { city: "BHIMPHEDI", rate: 245.0 },
  { city: "BHINGRI PYUTHAN", rate: 275.0 },
  { city: "BHOJPUR", rate: 275.0 },
  { city: "BHOKRAHA", rate: 200.0 },
  { city: "BHURIGOAN", rate: 225.0 },
  { city: "BIDUR", rate: 225.0 },
  { city: "BINDABASINI PARSA", rate: 225.0 },
  { city: "BIRATCHOWK", rate: 200.0 },
  { city: "BIRATNAGAR", rate: 150.0 },
  { city: "BIRENDRA BAZAR DHANUSHA", rate: 225.0 },
  { city: "BIRGUNJ", rate: 200.0 },
  { city: "BIRTAMOD", rate: 200.0 },
  { city: "BISHNUPUR SAPTARI", rate: 225.0 },
  { city: "BISHNUPUR SIRAHA", rate: 225.0 },
  { city: "BODEBARSAIN SAPTARI", rate: 220.0 },
  { city: "BRAHAMPURI", rate: 225.0 },
  { city: "BRAHMADEV BAZAR", rate: 220.0 },
  { city: "BUDHABARE", rate: 225.0 },
  { city: "BUDOR DOTI", rate: 250.0 },
  { city: "BURTIBANG", rate: 250.0 },
  { city: "BUTWAL", rate: 150.0 },
  { city: "CHAINPUR BAJHANG", rate: 275.0 },
  { city: "CHAINPUR SANKHUWASABHA", rate: 275.0 },
  { city: "CHAKARGHATTI", rate: 225.0 },
  { city: "CHAKRAGHATTA SARLAHI", rate: 225.0 },
  { city: "CHAME MANANG", rate: 275.0 },
  { city: "CHANAULI", rate: 220.0 },
  { city: "CHANDRANIGAHAPUR", rate: 225.0 },
  { city: "CHANDRAUTA", rate: 225.0 },
  { city: "CHANGUNARAYAN BHAKTAPUR", rate: 150.0 },
  { city: "CHANHI BAZAR", rate: 225.0 },
  { city: "CHAPAGAUN", rate: 150.0 },
  { city: "CHARAALI", rate: 200.0 },
  { city: "CHARANGE RUPANDEHI", rate: 175.0 },
  { city: "CHARIKOT", rate: 225.0 },
  { city: "CHATARA", rate: 225.0 },
  { city: "CHAUMALA", rate: 220.0 },
  { city: "CHAUTARA", rate: 250.0 },
  { city: "CHINCHU", rate: 225.0 },
  { city: "CHISAPANI", rate: 225.0 },
  { city: "CHORMARA", rate: 200.0 },
  { city: "CHULACHULI ILLAM", rate: 250.0 },
  { city: "DAIJEE KANCHANPUR", rate: 225.0 },
  { city: "DAILEKH BAZAR", rate: 250.0 },
  { city: "DAKSHINKALI", rate: 150.0 },
  { city: "DALDALE", rate: 200.0 },
  { city: "DAMAK", rate: 200.0 },
  { city: "DAMAN", rate: 250.0 },
  { city: "DAMAR CHOWK RAUTAHAT", rate: 225.0 },
  { city: "DAMAULI", rate: 200.0 },
  { city: "DAMRABHITTA", rate: 225.0 },
  { city: "DANDA BAZAR", rate: 250.0 },
  { city: "DARCHULA KHALANGA", rate: 270.0 },
  { city: "DARWANG MYAGDI", rate: 250.0 },
  { city: "DASDHUNGA", rate: 200.0 },
  { city: "DEWANGANJ", rate: 225.0 },
  { city: "DHADING BESI", rate: 225.0 },
  { city: "DHAKDAI RUPANDEHI", rate: 220.0 },
  { city: "DHALKEBAR", rate: 200.0 },
  { city: "DHANGADHI", rate: 200.0 },
  { city: "DHANGADHIMAI SIRAHA", rate: 225.0 },
  { city: "DHANKAUL", rate: 225.0 },
  { city: "DHANKUTA", rate: 275.0 },
  { city: "DHANUSADHAM", rate: 225.0 },
  { city: "DHARAN", rate: 200.0 },
  { city: "DHULABARI", rate: 225.0 },
  { city: "DHULIKHEL", rate: 150.0 },
  { city: "DHUNCHE RASUWA", rate: 250.0 },
  { city: "DIKTEL KHOTANG", rate: 275.0 },
  { city: "DIMAN", rate: 225.0 },
  { city: "DINGLA BHOJPUR", rate: 275.0 },
  { city: "DIPAYAL BAZAR", rate: 275.0 },
  { city: "DODHARA CHANDANI KANCHANPUR", rate: 250.0 },
  { city: "DOLALGHAT KAVRE", rate: 250.0 },
  { city: "DUDHAULI SINDHULI", rate: 225.0 },
  { city: "DUHABI", rate: 200.0 },
  { city: "DUIPIPLE", rate: 275.0 },
  { city: "DULEGAUNDA TANAHU", rate: 200.0 },
  { city: "DULLU", rate: 295.0 },
  { city: "DUMKIBAS", rate: 200.0 },
  { city: "DUMRE", rate: 200.0 },
  { city: "DUNAI DOLPA", rate: 275.0 },
  { city: "FIKKAL", rate: 225.0 },
  { city: "GADDA CHAUKI", rate: 250.0 },
  { city: "GADHAWA", rate: 225.0 },
  { city: "GAIDAKOT", rate: 200.0 },
  { city: "GAIGHAT", rate: 225.0 },
  { city: "GAIR SARLAHI", rate: 225.0 },
  { city: "GAJURI", rate: 225.0 },
  { city: "GALCHI", rate: 225.0 },
  { city: "GALKOT", rate: 225.0 },
  { city: "GAMGADHI MUGU", rate: 275.0 },
  { city: "GANESHPUR KAPILBASTU", rate: 225.0 },
  { city: "GANESHPUR SIRAHA", rate: 225.0 },
  { city: "GARAMANI JHAPA", rate: 225.0 },
  { city: "GARUDA", rate: 225.0 },
  { city: "GAUR", rate: 225.0 },
  { city: "GAURADAHA", rate: 225.0 },
  { city: "GAURIGANJ", rate: 225.0 },
  { city: "GAUSHALA MAHOTTARI", rate: 225.0 },
  { city: "GETA KAILALI", rate: 225.0 },
  { city: "GHORAHI", rate: 200.0 },
  { city: "GODAITA SARLAHI", rate: 225.0 },
  { city: "GODAWARI KAILALI", rate: 225.0 },
  { city: "GODAWARI LALITPUR", rate: 150.0 },
  { city: "GOGALI DANG", rate: 250.0 },
  { city: "GOKULESHWOR DARCHULA", rate: 275.0 },
  { city: "GOLBAZAR", rate: 225.0 },
  { city: "GOLDHAP JHAPA", rate: 225.0 },
  { city: "GOLDUBA", rate: 225.0 },
  { city: "GOPIGUNJ JAMUNIYA", rate: 250.0 },
  { city: "GORKHA BAZAR", rate: 225.0 },
  { city: "GORUSINGE", rate: 225.0 },
  { city: "GOTHALAPANI BAITADI", rate: 275.0 },
  { city: "GULARIYA", rate: 225.0 },
  { city: "GULARIYA KANCHANPUR", rate: 250.0 },
  { city: "HAKPARA", rate: 225.0 },
  { city: "HALDIBARI JHAPA", rate: 225.0 },
  { city: "HALESI", rate: 275.0 },
  { city: "HANUMANNAGR SAPTARI", rate: 225.0 },
  { city: "HAPURE", rate: 225.0 },
  { city: "HARINAGRA", rate: 200.0 },
  { city: "HARIPUR SARLAHI", rate: 225.0 },
  { city: "HARIWAN", rate: 225.0 },
  { city: "HARKAPUR 16 NO", rate: 250.0 },
  { city: "HASULIYA KAILALI", rate: 225.0 },
  { city: "HEAD OFFICE", rate: 120.0 },
  { city: "HEAD OFFICE (BHAKTAPUR)", rate: 120.0 },
  { city: "HEAD OFFICE (KATHMANDU)", rate: 120.0 },
  { city: "HEAD OFFICE (LALITPUR)", rate: 120.0 },
  { city: "HEKULI", rate: 220.0 },
  { city: "HEMJA", rate: 225.0 },
  { city: "HETAUDA", rate: 200.0 },
  { city: "HILE", rate: 275.0 },
  { city: "ILLAM", rate: 225.0 },
  { city: "IMILIYA KAPILBASTU", rate: 250.0 },
  { city: "INARUWA", rate: 200.0 },
  { city: "ITAHARI", rate: 150.0 },
  { city: "JAGARNATHPUR", rate: 200.0 },
  { city: "JAGATPUR CHITWAN", rate: 200.0 },
  { city: "JAJARKOT KHALANGA", rate: 275.0 },
  { city: "JALESHWOR", rate: 225.0 },
  { city: "JANAKPUR", rate: 200.0 },
  { city: "JAYANAGAR BARDIYA", rate: 250.0 },
  { city: "JEETPUR BARA", rate: 225.0 },
  { city: "JHALARI", rate: 250.0 },
  { city: "JHAPA BAZAR", rate: 225.0 },
  { city: "JHILJHILE JHAPA", rate: 225.0 },
  { city: "JHUMKA SUNSARI", rate: 200.0 },
  { city: "JIRI DOLAKHA", rate: 250.0 },
  { city: "JIRIKHIMTI", rate: 250.0 },
  { city: "JOGIKUTI", rate: 200.0 },
  { city: "JOMSOM", rate: 275.0 },
  { city: "JORPOKHARI PANCHTHAR", rate: 250.0 },
  { city: "JOSHIPUR", rate: 250.0 },
  { city: "JUGEDA KAILALI", rate: 250.0 },
  { city: "JUGEDI CHITWAN", rate: 200.0 },
  { city: "JUMLA KHALANGA", rate: 275.0 },
  { city: "KADMAHA SAPTARI", rate: 225.0 },
  { city: "KAKARBHITTA", rate: 225.0 },
  { city: "KALABANJAR", rate: 225.0 },
  { city: "KALAIYA", rate: 225.0 },
  { city: "KALYANPUR SAPTARI", rate: 250.0 },
  { city: "KALYANPUR SIRAHA", rate: 250.0 },
  { city: "KAMAL BAZAR", rate: 295.0 },
  { city: "KANCHANPUR SAPTARI", rate: 225.0 },
  { city: "KANCHI BAZAR", rate: 220.0 },
  { city: "KANEPOKHARI", rate: 250.0 },
  { city: "KANYAM", rate: 250.0 },
  { city: "KARSIYA", rate: 225.0 },
  { city: "KASKI NAUDANDA", rate: 225.0 },
  { city: "KATAHARI MORANG", rate: 225.0 },
  { city: "KATARI", rate: 225.0 },
  { city: "KAUDENA", rate: 225.0 },
  { city: "KAWASOTI", rate: 200.0 },
  { city: "KECHANA JHAPA", rate: 250.0 },
  { city: "KERABARI MORANG", rate: 250.0 },
  { city: "KERKHA JHAPA", rate: 225.0 },
  { city: "KHAIRENI RUPANDEHI", rate: 225.0 },
  { city: "KHAJURA", rate: 250.0 },
  { city: "KHANDBARI", rate: 275.0 },
  { city: "KHAYARMARA", rate: 225.0 },
  { city: "KHUDI BAZAR", rate: 250.0 },
  { city: "KHUDUNABARI JHAPA", rate: 225.0 },
  { city: "KHURKHURE CHITWAN", rate: 225.0 },
  { city: "KHURKOT", rate: 250.0 },
  { city: "KOHALPUR", rate: 200.0 },
  { city: "KOLHABI BAZAR", rate: 250.0 },
  { city: "KOLTI", rate: 295.0 },
  { city: "KOTIHAWA", rate: 225.0 },
  { city: "KRISHNANAGAR", rate: 250.0 },
  { city: "KUSMA", rate: 225.0 },
  { city: "LABANI", rate: 200.0 },
  { city: "LAHAN", rate: 200.0 },
  { city: "LALBANDI", rate: 225.0 },
  { city: "LALJHADI", rate: 225.0 },
  { city: "LAMAHI", rate: 225.0 },
  { city: "LAMKI", rate: 225.0 },
  { city: "LAUKAHI SUNSARI", rate: 225.0 },
  { city: "LAXMIPUR JHAPA", rate: 225.0 },
  { city: "LAXMIPUR PATARI", rate: 225.0 },
  { city: "LEKHNATH", rate: 200.0 },
  { city: "LELE LALITPUR", rate: 150.0 },
  { city: "LETANG", rate: 250.0 },
  { city: "LIWANG", rate: 250.0 },
  { city: "LOTHAR CHITWAN", rate: 250.0 },
  { city: "LUBHU LAMATAR", rate: 150.0 },
  { city: "LUHAM", rate: 250.0 },
  { city: "LUMBINI BAZAR", rate: 225.0 },
  { city: "MADHUMALLA MORANG", rate: 225.0 },
  { city: "MADI", rate: 250.0 },
  { city: "MAHADEVA SAPTARI", rate: 225.0 },
  { city: "MAHARAJGANJ KAPILBASTU", rate: 250.0 },
  { city: "MAHENDRANAGAR", rate: 225.0 },
  { city: "MAHENDRANAGAR DHANUSA", rate: 225.0 },
  { city: "MAHESHPUR THUTHIBARI", rate: 225.0 },
  { city: "MAHULI", rate: 225.0 },
  { city: "MAIDHAR JHAPA", rate: 225.0 },
  { city: "MAINA POKHAR BARDIYA", rate: 250.0 },
  { city: "MAINAPOKHARI DOLAKHA", rate: 275.0 },
  { city: "MALANGWA", rate: 225.0 },
  { city: "MALEKHU", rate: 225.0 },
  { city: "MANAHARI MAKWANPUR", rate: 250.0 },
  { city: "MANARA", rate: 225.0 },
  { city: "MANGALBARE ILLAM", rate: 250.0 },
  { city: "MANGALSEN", rate: 275.0 },
  { city: "MANIGRAM", rate: 200.0 },
  { city: "MANMA", rate: 275.0 },
  { city: "MANTHALI", rate: 225.0 },
  { city: "MARTADI", rate: 275.0 },
  { city: "MASURIYA", rate: 250.0 },
  { city: "MATIHANI", rate: 225.0 },
  { city: "MAULAPUR", rate: 225.0 },
  { city: "MEGHAULI CHITWAN", rate: 200.0 },
  { city: "MEHELKUNA SURKHET", rate: 275.0 },
  { city: "MELAMCHI", rate: 250.0 },
  { city: "MIRCHAIYA", rate: 225.0 },
  { city: "MOTIPUR", rate: 250.0 },
  { city: "MOURIGHAT", rate: 225.0 },
  { city: "MUGLING", rate: 200.0 },
  { city: "MURGIYA", rate: 225.0 },
  { city: "MUSIKOT", rate: 275.0 },
  { city: "MYANGLUNG BAZAR", rate: 250.0 },
  { city: "NAGARAIN DHANUSHA", rate: 225.0 },
  { city: "NAGARKOT", rate: 200.0 },
  { city: "NAGDHUNGA", rate: 175.0 },
  { city: "NARAHA", rate: 225.0 },
  { city: "NARAYANGARH", rate: 150.0 },
  { city: "NARAYANPUR", rate: 250.0 },
  { city: "NAUBISE", rate: 200.0 },
  { city: "NAYAPUL KUSMA", rate: 275.0 },
  { city: "NEPALGUNJ", rate: 200.0 },
  { city: "NEPALTAR ILLAM", rate: 225.0 },
  { city: "NETA CHOWK MORANG", rate: 225.0 },
  { city: "NIJGADH", rate: 225.0 },
  { city: "ODARI KAPILBASTU", rate: 225.0 },
  { city: "OKHALDHUNGA", rate: 275.0 },
  { city: "PADAM POKHARI", rate: 225.0 },
  { city: "PADAMPUR CHITWAN", rate: 225.0 },
  { city: "PAHALBANPUR", rate: 225.0 },
  { city: "PAKADI", rate: 225.0 },
  { city: "PAKHRIBAS DHANKUTA", rate: 275.0 },
  { city: "PALUNGTAR", rate: 250.0 },
  { city: "PAME", rate: 170.0 },
  { city: "PANAUTI", rate: 150.0 },
  { city: "PANCHKHAL KAVRE", rate: 225.0 },
  { city: "PARABARI JHAPA", rate: 225.0 },
  { city: "PARASI", rate: 225.0 },
  { city: "PARSA CHITWAN", rate: 225.0 },
  { city: "PASHUPATINAGAR", rate: 250.0 },
  { city: "PATAN BAITADI", rate: 295.0 },
  { city: "PATHARI", rate: 225.0 },
  { city: "PATHLAIYA", rate: 225.0 },
  { city: "PATO", rate: 225.0 },
  { city: "PHARSATIKAR", rate: 250.0 },
  { city: "PHATTEPUR SAPTARI", rate: 250.0 },
  { city: "PHIDIM", rate: 225.0 },
  { city: "PHULBARI KAILALI", rate: 250.0 },
  { city: "PILUWA", rate: 250.0 },
  { city: "PIPRAHAWA", rate: 225.0 },
  { city: "POKHARA", rate: 150.0 },
  { city: "POKHARIYA", rate: 250.0 },
  { city: "PRAKASHPUR SUNSARI", rate: 225.0 },
  { city: "PUNARBAS KANCHANPUR", rate: 250.0 },
  { city: "PURANO SUKRABARE", rate: 225.0 },
  { city: "PUTALI CHOWK SARLAHI", rate: 225.0 },
  { city: "PYUTHAN", rate: 250.0 },
  { city: "PYUTHAN KHALANGA", rate: 275.0 },
  { city: "RAJAHAR NAWALPARASI", rate: 225.0 },
  { city: "RAJAPUR", rate: 225.0 },
  { city: "RAJARANI DHANKUTA", rate: 250.0 },
  { city: "RAJBIRAJ", rate: 200.0 },
  { city: "RAJDEVI RAUTAHAT", rate: 225.0 },
  { city: "RAJGADH JHAPA", rate: 225.0 },
  { city: "RAMAILO MORANG", rate: 250.0 },
  { city: "RAMGOPALPUR", rate: 225.0 },
  { city: "RAMPUR PALPA", rate: 225.0 },
  { city: "RAMPUR UDAYAPUR", rate: 250.0 },
  { city: "RANGELI", rate: 200.0 },
  { city: "RANKE", rate: 250.0 },
  { city: "RETURN HEAD OFFICE OLD", rate: 120.0 },
  { city: "RIDI", rate: 250.0 },
  { city: "RUDRAPUR HARAIYA RUPANDEHI", rate: 250.0 },
  { city: "RUKUM CHAURJAHARI", rate: 275.0 },
  { city: "RUKUMKOT", rate: 275.0 },
  { city: "RUPANI", rate: 225.0 },
  { city: "RUPNAGAR", rate: 225.0 },
  { city: "SABAILA DHANUSHA", rate: 225.0 },
  { city: "SAKHADA CHHINNAMASTA", rate: 225.0 },
  { city: "SALLERI (SOLU)", rate: 275.0 },
  { city: "SALYAN KHALANGA", rate: 225.0 },
  { city: "SAMSHERGUNJ", rate: 250.0 },
  { city: "SAMSI MAHOTTARI", rate: 225.0 },
  { city: "SANDHIKHARKA", rate: 225.0 },
  { city: "SANFEBAGAR ACHHAM", rate: 275.0 },
  { city: "SANGRAMPUR", rate: 225.0 },
  { city: "SANISCHARE JHAPA", rate: 225.0 },
  { city: "SANKHU", rate: 150.0 },
  { city: "SAPAHI", rate: 225.0 },
  { city: "SATTI BAZAR", rate: 250.0 },
  { city: "SAURAHA CHITWAN", rate: 225.0 },
  { city: "SCHOOL CHOWN JHAPA", rate: 225.0 },
  { city: "SHAKTIKHOR CHITWAN", rate: 225.0 },
  { city: "SHANTIPUR GULMI", rate: 275.0 },
  { city: "SHARANMATI JHAPA", rate: 250.0 },
  { city: "SHIVAGUNJ JHAPA", rate: 250.0 },
  { city: "SHREE ANTU", rate: 250.0 },
  { city: "SHREENAGAR SALYAN", rate: 250.0 },
  { city: "SIDHUWA DHANKUTA", rate: 275.0 },
  { city: "SILGADHI", rate: 275.0 },
  { city: "SIMARA", rate: 225.0 },
  { city: "SIMIKOT HUMLA", rate: 295.0 },
  { city: "SINDHULI", rate: 200.0 },
  { city: "SIRAHA BAZAR", rate: 250.0 },
  { city: "SOMBARE MORANG", rate: 250.0 },
  { city: "SUKHIPUR SIRAHA", rate: 225.0 },
  { city: "SUKKHAD", rate: 225.0 },
  { city: "SULICHAUR", rate: 250.0 },
  { city: "SUNDAR BAZAR", rate: 250.0 },
  { city: "SUNDARIJAL", rate: 150.0 },
  { city: "SUNWAL", rate: 200.0 },
  { city: "SUNWARSHI MORANG", rate: 250.0 },
  { city: "SURKHET", rate: 225.0 },
  { city: "SURUNGA", rate: 225.0 },
  { city: "SYANGJA BAYARGHARI", rate: 250.0 },
  { city: "SYANGJA CHAPAKOT", rate: 225.0 },
  { city: "SYANGJA GALYANG", rate: 225.0 },
  { city: "SYANGJA PUTALIBAZAR", rate: 225.0 },
  { city: "SYANGJA WALING", rate: 200.0 },
  { city: "SYAULE BAZAR KAILALI", rate: 225.0 },
  { city: "TAMGHAS", rate: 225.0 },
  { city: "TAMNAGAR", rate: 225.0 },
  { city: "TANDI", rate: 200.0 },
  { city: "TANKI MORANG", rate: 175.0 },
  { city: "TANSEN", rate: 200.0 },
  { city: "TAPLEJUNG BAZAR", rate: 295.0 },
  { city: "TARAHARA SUNSARI", rate: 200.0 },
  { city: "TARATAL BARDIYA", rate: 250.0 },
  { city: "TAULIHAWA", rate: 225.0 },
  { city: "THARMARE", rate: 225.0 },
  { city: "THUTIPIPAL", rate: 200.0 },
  { city: "TIKAPUR", rate: 225.0 },
  { city: "TINGLA (SOLU)", rate: 275.0 },
  { city: "TINKORIYA DHANUSHA", rate: 225.0 },
  { city: "TOPA BAZAR", rate: 225.0 },
  { city: "TRISHULI", rate: 225.0 },
  { city: "TULSIPUR", rate: 200.0 },
  { city: "TUMLINGTAR", rate: 275.0 },
  { city: "TUTESHWAR MAHOTTARI", rate: 250.0 },
  { city: "URALABARI", rate: 200.0 },
  { city: "WAMISTASKAR", rate: 245.0 },
  { city: "YADUKUHA DHANUSHA", rate: 225.0 },
];
